services:
  # Django web application
  web:
    container_name: mkriyada_app
    build:
      context: ./project
      dockerfile: ./Dockerfile
    volumes:
      - staticfiles:/neksio/static/
    env_file:
      - ./.env
    ports:
       - '8000:8000'
    depends_on:
      - db
      - redis
    networks:
      - shared_network

  redis:
     image: redis:alpine
     container_name: redis_server
     ports:
       - "6379:6379"

     volumes:
       - redis_data:/data

     networks:
       - shared_network

  db:
    image: postgres
    container_name: postgres_mkriyada
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - shared_network

#  nginx:
#    container_name: nginx
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - web
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#      - staticfiles:/static/
#    networks:
#      - shared_network
volumes:
  postgres_data:
  staticfiles:
  redis_data:


networks:
  shared_network:
    driver: bridge