# Generated by Django 5.2.5 on 2025-08-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='payment_term',
            field=models.CharField(blank=True, max_length=100, verbose_name='Payment Term'),
        ),
    ]
