# Generated by Django 5.2.5 on 2025-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customerdetail_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='building_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Building Number'),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='city_subdivision_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City Subdivision Name'),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='registered_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registered Name'),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Name'),
        ),
    ]
