# Generated by Django 5.2.5 on 2025-08-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invoice_due_date_invoice_sub_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='best_for',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='invoice_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='number_of_users',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='support_level',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
