# Generated by Django 5.2.5 on 2025-08-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_currencycodes_invoice_currency_paymentterms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='customer_no',
            new_name='serial_no',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_number',
            new_name='serial_no',
        ),
    ]
