# Generated by Django 5.2.5 on 2025-08-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_customer_no_customerdetail_serial_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transaction_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELED')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], max_length=500, null=True),
        ),
    ]
