# Generated by Django 5.2.5 on 2025-08-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_invoice_transaction_status_invoice_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinvoice',
            old_name='rate',
            new_name='price',
        ),
    ]
