# Generated by Django 5.2.5 on 2025-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_rate_productinvoice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinvoice',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
