# Generated by Django 5.2.5 on 2025-09-01 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_productinvoice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencycodes',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='api.company'),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='api.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='api.company'),
        ),
        migrations.AlterField(
            model_name='paymentterms',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='api.company'),
        ),
        migrations.AlterField(
            model_name='productinvoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='api.company'),
        ),
    ]
