# Generated by Django 5.2.5 on 2025-09-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_currencycodes_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enabled_zatca',
            field=models.BooleanField(default=False),
        ),
    ]
