# Generated by Django 5.2.5 on 2025-09-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_company_tax_no_invoice_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_return',
            field=models.BooleanField(default=False, verbose_name='Return Invoice'),
        ),
    ]
