# Generated by Django 5.2.6 on 2025-09-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_customerdetail_email_customerdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='email',
            field=models.CharField(blank=True, max_length=150, verbose_name='Customer Email'),
        ),
    ]
