# Generated by Django 5.2.6 on 2025-09-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_customerdetail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_invoices',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='max_users',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
