# Generated by Django 5.2.6 on 2025-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_company_max_invoices_company_max_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='action',
            field=models.CharField(blank=True, choices=[('extend', 'Extend'), ('suspend', 'Suspend'), ('reactivate', 'Reactivate')], max_length=10, null=True),
        ),
    ]
