# Generated by Django 5.2.6 on 2025-09-22 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_company_action'),
        ('product', '0008_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AddField(
            model_name='company',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficiary Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='city_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City in Arabic'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Contact Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_address_details', to='api.country'),
        ),
        migrations.AddField(
            model_name='company',
            name='country_iso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country ISO'),
        ),
        migrations.AddField(
            model_name='company',
            name='district_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company District in Arabic'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Contact Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='iban_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IBAN Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='media_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_media_files', to='product.mediafiles'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ar',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Company Name in Arabic'),
        ),
        migrations.AddField(
            model_name='company',
            name='portal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Portal'),
        ),
        migrations.AddField(
            model_name='company',
            name='street_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='street_name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Name in Arabic'),
        ),
        migrations.AddField(
            model_name='company',
            name='swift_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Swift Code'),
        ),
        migrations.AddField(
            model_name='company',
            name='zatca_phase',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Zatca Phase'),
        ),
        migrations.AddField(
            model_name='company',
            name='zatca_phase_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Company Zatca Phase 2 Start Date'),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='address_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Customer Address Arabic'),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='street_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Name Arabic'),
        ),
        migrations.AlterField(
            model_name='company',
            name='action',
            field=models.CharField(blank=True, choices=[('extend', 'Extend'), ('suspend', 'Suspend'), ('reactivate', 'Reactivate')], max_length=10, null=True, verbose_name='Company Action'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company API Key'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company District'),
        ),
        migrations.AlterField(
            model_name='company',
            name='enabled_zatca',
            field=models.BooleanField(default=False, verbose_name='Company Zatca Enabled'),
        ),
        migrations.AlterField(
            model_name='company',
            name='expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Company Expiry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='max_invoices',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Company Max Invoices'),
        ),
        migrations.AlterField(
            model_name='company',
            name='max_users',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Company Max Users'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Company Phone Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sandbox_secret_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Sandbox Secret Key'),
        ),
        migrations.AlterField(
            model_name='company',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Secret Key'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Company Tax No'),
        ),
    ]
