# Generated by Django 5.2.6 on 2025-09-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_company_options_company_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='district',
            field=models.CharField(blank=True, max_length=50, verbose_name='Customer District'),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='district_ar',
            field=models.CharField(blank=True, max_length=50, verbose_name='Customer District Arabic'),
        ),
    ]
