# Generated by Django 5.2.6 on 2025-09-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_customerdetail_district_customerdetail_district_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='portal',
            field=models.CharField(blank=True, choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=100, null=True, verbose_name='Company Portal'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zatca_phase',
            field=models.CharField(blank=True, choices=[('1', 'Phase 1'), ('2', 'Phase 2')], max_length=100, null=True, verbose_name='Company Zatca Phase'),
        ),
    ]
