# Generated by Django 5.2.6 on 2025-09-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_company_portal_alter_company_zatca_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_country', to='api.country', verbose_name='Country'),
        ),
    ]
