# Generated by Django 5.2.6 on 2025-09-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_customerdetail_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_country', to='api.country', verbose_name='Country'),
        ),
    ]
