# Generated by Django 5.2.6 on 2025-10-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_customerdetail_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
