# Generated by Django 5.2.6 on 2025-10-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_invoice_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='production_enable_zatca',
            field=models.BooleanField(default=False, verbose_name='Company Zatca Production Enabled'),
        ),
    ]
