# Generated by Django 5.2.6 on 2025-10-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_company_production_enable_zatca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name in Arabic'),
        ),
    ]
