# Generated by Django 5.2.6 on 2025-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_company_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='bank_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Address'),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='iban_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IBAN Number'),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='swift_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Swift Code'),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('10', 'Cash,نقدي'), ('20', 'Cheque,شيك'), ('30', 'Credit,ذمم'), ('42', 'Bank Transfer,حوالة بنكية'), ('48', 'Bank Card, Visa Mada'), ('1', 'Instrument not defined,اخرى')], max_length=100, verbose_name='Payment Methods'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.TextField(blank=True, choices=[('10', 'Cash,نقدي'), ('20', 'Cheque,شيك'), ('30', 'Credit,ذمم'), ('42', 'Bank Transfer,حوالة بنكية'), ('48', 'Bank Card, Visa Mada'), ('1', 'Instrument not defined,اخرى')], null=True),
        ),
    ]
