# Generated by Django 5.2.6 on 2025-10-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_customerdetail_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='license_type',
            field=models.CharField(blank=True, choices=[('CRN', 'CRN'), ('VAT', 'VAT'), ('TIN', 'TIN'), ('GCC', 'GCC'), ('IQA', 'IQA'), ('PAS', 'PAS'), ('CRN', 'CRN'), ('MOM', 'MOM'), ('MLS', 'MLS'), ('700', '700'), ('SAG', 'SAG'), ('OTH', 'OTH')], max_length=50, verbose_name='License Type'),
        ),
    ]
