# Generated by Django 5.2.6 on 2025-10-27 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_customerdetail_license_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentterms',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='payment_term',
        ),
        migrations.RemoveField(
            model_name='paymentterms',
            name='company',
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='payment_terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment_terms', to='api.paymentterms'),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_currency', to='api.currencycodes'),
        ),
    ]
