# Generated by Django 5.2.6 on 2025-11-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_taxtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinvoice',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_value', to='api.taxtype'),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='tax_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Category'),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='vat_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VAT Group'),
        ),
    ]
