# Generated by Django 5.2.6 on 2025-11-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_productinvoice_tax_type_taxtype_tax_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='Customer City'),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='city_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='Customer City Arabic'),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='district',
            field=models.CharField(blank=True, max_length=150, verbose_name='Customer District'),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='district_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='Customer District Arabic'),
        ),
    ]
