# Generated by Django 5.2.5 on 2025-08-28 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_customerdetail_building_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(blank=True, max_length=230)),
                ('file', models.FileField(upload_to='static/uploads/')),
                ('file_type', models.CharField(blank=True, choices=[('image', 'image'), ('pdf', 'pdf'), ('icons', 'icons'), ('other', 'other')], max_length=30)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='static/uploads/thumbnail/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_data', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_data', to='api.company')),
                ('media_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.mediafiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('unit_value', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_data', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_no', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item_type', models.CharField(blank=True, choices=[('inventory', 'Inventory'), ('service', 'Service'), ('non_inventory', 'Non-Inventory')], max_length=100)),
                ('tax_applied', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=250)),
                ('promo_code', models.CharField(blank=True, max_length=250)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_data', to='api.company')),
                ('media_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_file', to='product.mediafiles')),
                ('umo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_umo', to='product.unitofmeasurements')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
