# Generated by Django 5.2.5 on 2025-08-30 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('invoice_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_users', models.PositiveIntegerField(blank=True, null=True)),
                ('api_access', models.BooleanField(default=False)),
                ('support_level', models.CharField(blank=True, max_length=255)),
                ('best_for', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
