# Generated by Django 5.2.5 on 2025-08-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_subscriptionplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitems',
            old_name='item_no',
            new_name='serial_no',
        ),
    ]
