# Generated by Django 5.2.5 on 2025-09-01 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_currencycodes_company_and_more'),
        ('product', '0004_rename_item_no_productitems_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='api.company'),
        ),
        migrations.AlterField(
            model_name='mediafiles',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='api.company'),
        ),
        migrations.AlterField(
            model_name='productitems',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='api.company'),
        ),
        migrations.AlterField(
            model_name='unitofmeasurements',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='api.company'),
        ),
    ]
