# Generated by Django 5.2.6 on 2025-09-13 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_customerdetail_email_customerdetail_user'),
        ('product', '0005_alter_category_company_alter_mediafiles_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('recipient', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.CharField(blank=True, choices=[('Email', 'Email'), ('SMS', 'SMS')], default='Email', max_length=200, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
