# Generated by Django 5.2.6 on 2025-09-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_notificationcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcenter',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
