# Generated by Django 5.2.6 on 2025-10-01 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_customerdetail_country'),
        ('product', '0008_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitems',
            name='sku',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='ItemTags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productitems',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='item_tags', to='product.itemtags'),
        ),
    ]
