# Generated by Django 5.2.5 on 2025-09-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_status'),
        ('api', '0010_alter_productinvoice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company'),
        ),
    ]
