# Generated by Django 5.2.5 on 2025-09-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_users_created_at_users_updated_at'),
        ('api', '0016_remove_customerdetail_email_customerdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.company'),
        ),
    ]
