# Generated by Django 5.2.6 on 2025-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_users_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
